### ISSUE TITLE
Что за модуль registration - все ли зависимости указаны в requirements.txt?

### ISSUE THREAD

**Issue by victor-yacovlev** [AmatanHead/collective-blog#1]
Используется Python 2.7.9, все зависимости из `requirements.txt` установлены успешно с помощью `pip`.

```
> python manage.py makemigrations
Loading development settings
Warning: no secret key set!
Warning: no recaptcha public key set!
Warning: no recaptcha key set!
Warning: recaptcha is running in the debug mode!
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/usr/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/lib/python2.7/site-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named registration

```

**Comment by AmatanHead** [comment]
Это странно. Только что запустил [билд](https://travis-ci.org/AmatanHead/collective-blog), всё ок. Что говорит `pip freeze`? есть ли лог, оставшийся от `pip install`? Похоже, не установился `django-registration-redux`, но он есть в зависимостях.

**Comment by victor-yacovlev** [comment]
```
> pip freeze | grep django
django-ckeditor==5.0.3
django-fake-model==0.1.4
django-messages-extends==0.5
django-mptt==0.8.6
django-recaptcha==1.0.5
django-registration-redux==1.4
django-taggit==0.20.2
django-uuslug==1.1.8
```

**Comment by victor-yacovlev** [comment]
Сорри, у меня дефолтным оказался pip == pip3.4
